export const DROP_TABLE_FIRST_TIME = `DROP TABLE IF EXISTS FIRST_TIME; `

export const CREATE_TABLE_FIRST_TIME = `CREATE TABLE IF NOT EXISTS FIRST_TIME (
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
YES BOOLEAN NOT NULL);`;